### ISSUE TITLE
Homebridge general issue when A/C does not respond

### ISSUE THREAD

**Issue by peros550** [SebastianOsinski/HomebridgePluginSamsungAirConditioner#6] opened 2018-10-19 09:58 UTC
Hi Sebastian, 

I 'm getting the below error. I'm currently not at home, so maybe the problem could be on the A/C side. However, this error makes Homebridge to not respond at all making all other accessories in the same page unavailable. If I open home app on another room, where there is no A/C, homebridge provides updates for the status of the rest accessories without issues.  

Perhaps some improved error handling  could help in the situation?

Many thanks for your efforts. You have a helped us a lot. If you need more information, or if I can do something to help , please let me know. 

```
Oct 19 09:52:45 raspberrypi homebridge[7529]: [2018-10-19 09:52:45] [Air Conditioner] Getting target temperature...
Oct 19 09:52:45 raspberrypi homebridge[7529]: [2018-10-19 09:52:45] [Air Conditioner] Write:  <Request Type="DeviceState"><DUID="BC8CCD5B                   8905"><Attr ID="AC_FUN_TEMPSET" /></Request>
Oct 19 09:52:45 raspberrypi homebridge[7529]: [2018-10-19 09:52:45] [Air Conditioner] Error: This socket is closed
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Socket._writeGeneric (net.js:733:18)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Socket._write (net.js:787:8)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at doWrite (_stream_writable.js:396:12)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at writeOrBuffer (_stream_writable.js:382:5)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Writable.write (_stream_writable.js:290:11)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Socket.write (net.js:711:40)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at AirConditionerApi._send (/usr/lib/node_modules/homebridge-plugin-samsung-air-conditi                   oner/air-conditioner-api.js:102:17)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at AirConditionerApi.deviceState (/usr/lib/node_modules/homebridge-plugin-samsung-air-c                   onditioner/air-conditioner-api.js:95:10)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at AirConditioner.getTargetTemperature (/usr/lib/node_modules/homebridge-plugin-samsung                   -air-conditioner/index.js:138:18)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at emitThree (events.js:136:13)
Oct 19 09:52:45 raspberrypi homebridge[7529]: [2018-10-19 09:52:45] [Air Conditioner] Getting active...
Oct 19 09:52:45 raspberrypi homebridge[7529]: [2018-10-19 09:52:45] [Air Conditioner] Write:  <Request Type="DeviceState"><DUID="BC8CCD5B                   8905"><Attr ID="AC_FUN_POWER" /></Request>
Oct 19 09:52:45 raspberrypi homebridge[7529]: [2018-10-19 09:52:45] [Air Conditioner] Error: This socket is closed
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Socket._writeGeneric (net.js:733:18)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Socket._write (net.js:787:8)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at doWrite (_stream_writable.js:396:12)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at writeOrBuffer (_stream_writable.js:382:5)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Writable.write (_stream_writable.js:290:11)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Socket.write (net.js:711:40)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at AirConditionerApi._send (/usr/lib/node_modules/homebridge-plugin-samsung-air-conditi                   oner/air-conditioner-api.js:102:17)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at AirConditionerApi.deviceState (/usr/lib/node_modules/homebridge-plugin-samsung-air-c                   onditioner/air-conditioner-api.js:95:10)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at AirConditioner.getActive (/usr/lib/node_modules/homebridge-plugin-samsung-air-condit                   ioner/index.js:106:18)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at emitThree (events.js:136:13)
Oct 19 09:52:45 raspberrypi homebridge[7529]: [2018-10-19 09:52:45] [Air Conditioner] Getting target temperature...
Oct 19 09:52:45 raspberrypi homebridge[7529]: [2018-10-19 09:52:45] [Air Conditioner] Write:  <Request Type="DeviceState"><DUID="BC8CCD5B                   8905"><Attr ID="AC_FUN_TEMPSET" /></Request>
Oct 19 09:52:45 raspberrypi homebridge[7529]: [2018-10-19 09:52:45] [Air Conditioner] Error: This socket is closed
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Socket._writeGeneric (net.js:733:18)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Socket._write (net.js:787:8)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at doWrite (_stream_writable.js:396:12)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at writeOrBuffer (_stream_writable.js:382:5)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Writable.write (_stream_writable.js:290:11)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Socket.write (net.js:711:40)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at AirConditionerApi._send (/usr/lib/node_modules/homebridge-plugin-samsung-air-conditi                   oner/air-conditioner-api.js:102:17)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at AirConditionerApi.deviceState (/usr/lib/node_modules/homebridge-plugin-samsung-air-c                   onditioner/air-conditioner-api.js:95:10)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at AirConditioner.getTargetTemperature (/usr/lib/node_modules/homebridge-plugin-samsung                   -air-conditioner/index.js:138:18)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at emitThree (events.js:136:13)
Oct 19 09:52:45 raspberrypi homebridge[7529]: [2018-10-19 09:52:45] [Air Conditioner] Getting swing mode...
Oct 19 09:52:45 raspberrypi homebridge[7529]: [2018-10-19 09:52:45] [Air Conditioner] Write:  <Request Type="DeviceState"><DUID="BC8CCD5B                   8905"><Attr ID="AC_FUN_DIRECTION" /></Request>
Oct 19 09:52:45 raspberrypi homebridge[7529]: [2018-10-19 09:52:45] [Air Conditioner] Error: This socket is closed
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Socket._writeGeneric (net.js:733:18)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Socket._write (net.js:787:8)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at doWrite (_stream_writable.js:396:12)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at writeOrBuffer (_stream_writable.js:382:5)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Writable.write (_stream_writable.js:290:11)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Socket.write (net.js:711:40)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at AirConditionerApi._send (/usr/lib/node_modules/homebridge-plugin-samsung-air-conditi                   oner/air-conditioner-api.js:102:17)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at AirConditionerApi.deviceState (/usr/lib/node_modules/homebridge-plugin-samsung-air-c                   onditioner/air-conditioner-api.js:95:10)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at AirConditioner.getSwingMode (/usr/lib/node_modules/homebridge-plugin-samsung-air-con                   ditioner/index.js:182:18)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at emitThree (events.js:136:13)
Oct 19 09:52:45 raspberrypi homebridge[7529]: [2018-10-19 09:52:45] [Air Conditioner] Getting current temperature...
Oct 19 09:52:45 raspberrypi homebridge[7529]: [2018-10-19 09:52:45] [Air Conditioner] Write:  <Request Type="DeviceState"><DUID="BC8CCD5B                   8905"><Attr ID="AC_FUN_TEMPNOW" /></Request>
Oct 19 09:52:45 raspberrypi homebridge[7529]: [2018-10-19 09:52:45] [Air Conditioner] Error: This socket is closed
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Socket._writeGeneric (net.js:733:18)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Socket._write (net.js:787:8)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at doWrite (_stream_writable.js:396:12)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at writeOrBuffer (_stream_writable.js:382:5)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Writable.write (_stream_writable.js:290:11)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Socket.write (net.js:711:40)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at AirConditionerApi._send (/usr/lib/node_modules/homebridge-plugin-samsung-air-conditi                   oner/air-conditioner-api.js:102:17)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at AirConditionerApi.deviceState (/usr/lib/node_modules/homebridge-plugin-samsung-air-c                   onditioner/air-conditioner-api.js:95:10)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at AirConditioner.getCurrentTemperature (/usr/lib/node_modules/homebridge-plugin-samsun                   g-air-conditioner/index.js:126:18)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at emitThree (events.js:136:13)
Oct 19 09:52:45 raspberrypi homebridge[7529]: [2018-10-19 09:52:45] [Air Conditioner] Getting target state...
Oct 19 09:52:45 raspberrypi homebridge[7529]: [2018-10-19 09:52:45] [Air Conditioner] Write:  <Request Type="DeviceState"><DUID="BC8CCD5B                   8905"><Attr ID="AC_FUN_OPMODE" /></Request>
Oct 19 09:52:45 raspberrypi homebridge[7529]: [2018-10-19 09:52:45] [Air Conditioner] Error: This socket is closed
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Socket._writeGeneric (net.js:733:18)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Socket._write (net.js:787:8)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at doWrite (_stream_writable.js:396:12)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at writeOrBuffer (_stream_writable.js:382:5)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Writable.write (_stream_writable.js:290:11)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at TLSSocket.Socket.write (net.js:711:40)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at AirConditionerApi._send (/usr/lib/node_modules/homebridge-plugin-samsung-air-conditi                   oner/air-conditioner-api.js:102:17)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at AirConditionerApi.deviceState (/usr/lib/node_modules/homebridge-plugin-samsung-air-c                   onditioner/air-conditioner-api.js:95:10)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at AirConditioner.getTargetState (/usr/lib/node_modules/homebridge-plugin-samsung-air-c                   onditioner/index.js:158:18)
Oct 19 09:52:45 raspberrypi homebridge[7529]:     at emitThree (events.js:136:13)
```

**Comment by SebastianOsinski** [comment] 2018-10-19 10:12
It's caused by disconnection from AC - either AC closed the connection or maybe there was a power loss. Current version of plugin doesn't handle socket closing correctly.

I already have PR opened for that: https://github.com/SebastianOsinski/HomebridgePluginSamsungAirConditioner/pull/3 
It should be available as release in near future.

**Comment by SebastianOsinski** [comment] 2018-10-20 06:30
@peros550 restarting Homebridge should help. After I release aforementioned PR, it shouldn’t be needed anymore. Token should stay the same, at least in case of my AC, it’s always the same each time I asked for it.

**Comment by peros550** [comment] 2018-10-20 09:57
You were right! I just rebooted raspberry and the issue disappeared. My  raspberry is feeded by UPS that’s why it didn’t reboot with the suspected power outage. 
Thanks

**Closed** 2018-10-25 18:30 UTC
Labels: bug
